### ISSUE TITLE
To'g'irlanishi muhim bo'lgan xatolar))

### ISSUE THREAD

**Issue by ghost** [1Farrukhbek/FIZZBUZZ-V2.0#1]
![image](https://user-images.githubusercontent.com/71978297/98637292-13b34580-234a-11eb-8612-97f7b97ae143.png)

Pusoy hamda harf kiritsam ham ishlab ketvoti 😉

**Comment by MrAbbosov** [comment]
Bu boshka proektniki. Va bu shundek ishlashi lozim. USTA😁
![Screenshot_20](https://user-images.githubusercontent.com/68499298/98772861-86372a80-2409-11eb-8c18-077ff3755741.png)
