### ISSUE TITLE
Sahifadagi scrollni yo'qotish kerak )

### ISSUE THREAD

**Issue by udilbar** [1Farrukhbek/FIZZBUZZ-V2.0#2]
![Screenshot_12](https://user-images.githubusercontent.com/68459485/98668197-5b999300-2371-11eb-8603-57b0fc3679fd.png)
Inputga kattaroq son kiritilanda, y o'qi bo'yicha scroll paydo bo'lyapti. Shuni yo'qotgan yaxshiroq )

**Comment by MrAbbosov** [comment]
Buni to'g'irlay olmadim. Bootstrapni bugi deb o'ylayman

**Comment by udilbar** [comment]
Body ga overflow-x ni hidden qilsak ishlasa kerak) Menimcha, bu Chromening kamchiligi, chuni Firefoxda sahifada scroll paydo bo'lmadi.

**Comment by MrAbbosov** [comment]
To'rgi rahmat
