### ISSUE TITLE
Inputga kiritilgan qiymatni tekshirishdagi kamchilik )

### ISSUE THREAD

**Issue by udilbar** [1Farrukhbek/FIZZBUZZ-V2.0#3]
![Screenshot_13](https://user-images.githubusercontent.com/68459485/98668523-d2369080-2371-11eb-8626-69bdd30f3772.png)
Inputga musbat son kiritilsa ham "is-invalid" classimiz turibdi, uni olib tashlaganimiz yaxshiroq )

**Comment by 1Farrukhbek** [comment]
![Uploading Screenshot_19.png…]()

**Comment by MrAbbosov** [comment]
Fixed
![Screenshot_19](https://user-images.githubusercontent.com/68499298/98772964-b8488c80-2409-11eb-85f5-3c7275b2b90c.png)
